// Export gate button set (review I12 / CIA F7). Run:
//   node --import ./tests/register-hooks.mjs tests/export-gate.test.mjs
//
// The gate used to render "Auto-fix and export" unconditionally, so clicking
// it on warnings nothing can fix (a group-scope `holes` result, an over-cap
// mesh, a bed-overflow warning) ran a repair batch that provably could not
// change anything and then exported anyway — which reads as "we fixed it".
//
// The markup is generated by a pure string function precisely so the button
// set, their order and their resolved `data-action` values are checkable
// without a DOM.

import assert from 'node:assert/strict';
import { installEnv } from './env.mjs';

installEnv();

const { exportGateActions, exportGateHtml, exportGateCanAutoFix } =
  await import('../src/ui/PrintPanel.js');
const { t } = await import('../src/i18n/index.js');

let passed = 0, failed = 0;
const out = [];
async function test(name, fn) {
  try { await fn(); out.push(`PASS  ${name}`); passed++; }
  catch (e) { out.push(`FAIL  ${name}\n      ${e.stack || e.message}`); failed++; }
}

/** `data-action` values in render order. */
function actionsInHtml(html) {
  return [...html.matchAll(/data-action="([a-z]+)"/g)].map(m => m[1]);
}

const geometryWarning = (objectIds) => ({
  code: 'geometry-warning', severity: 'warning', objectIds,
});
const bedWarning = { code: 'bed-overflow', severity: 'warning', objectIds: ['m1'] };

const stateWith = (validation) => ({ scene: { validation } });

await test('three buttons in order when something is fixable', () => {
  const issues = [geometryWarning(['m1'])];
  const state = stateWith({
    m1: { results: [{ type: 'holes', autoFixAvailable: true, fixed: false }], stale: false },
  });
  assert.equal(exportGateCanAutoFix(issues, state), true);
  assert.deepEqual(exportGateActions(true), ['autofix', 'export', 'cancel']);

  const html = exportGateHtml(issues, true);
  assert.deepEqual(actionsInHtml(html), ['autofix', 'export', 'cancel'],
    'Auto-fix is first (primary), then Export anyway, then Cancel');
  assert.match(html, /data-action="autofix">[^<]*Auto/i);
  assert.ok(html.includes(t('print.exportGate.fixAndExport')));
  assert.ok(html.includes(t('print.exportGate.exportAnyway')));
  assert.ok(html.includes(t('print.exportGate.cancel')));
  assert.equal((html.match(/class="btn btn-primary"/g) ?? []).length, 1,
    'exactly one primary button');
});

await test('I12: nothing fixable → a TWO-way gate, Auto-fix absent', () => {
  // A group-scope holes result: real geometry warning, but autoFixAvailable
  // is false because the repair applies per part, not to the welded union.
  const issues = [geometryWarning(['g1'])];
  const state = stateWith({
    g1: { results: [{ type: 'holes', autoFixAvailable: false, fixed: false, scope: 'group' }], stale: false },
  });
  assert.equal(exportGateCanAutoFix(issues, state), false);
  assert.deepEqual(exportGateActions(false), ['export', 'cancel']);

  const html = exportGateHtml(issues, false);
  assert.deepEqual(actionsInHtml(html), ['export', 'cancel']);
  assert.ok(!html.includes('data-action="autofix"'), 'no Auto-fix button at all');
  assert.ok(!html.includes(t('print.exportGate.fixAndExport')));
});

await test('I12: an already-applied fix is not "fixable" again', () => {
  const issues = [geometryWarning(['m1'])];
  const state = stateWith({
    m1: { results: [{ type: 'holes', autoFixAvailable: true, fixed: true }], stale: false },
  });
  assert.equal(exportGateCanAutoFix(issues, state), false);
});

await test('I12: warnings that are not geometry warnings never enable Auto-fix', () => {
  const state = stateWith({
    m1: { results: [{ type: 'holes', autoFixAvailable: true, fixed: false }], stale: false },
  });
  assert.equal(exportGateCanAutoFix([bedWarning], state), false,
    'a bed-overflow warning is not something the repair engine can fix');
});

await test('I12: no affected objects at all → no Auto-fix', () => {
  assert.equal(exportGateCanAutoFix([], stateWith({})), false);
  assert.equal(exportGateCanAutoFix([geometryWarning([])], stateWith({})), false);
  assert.equal(exportGateCanAutoFix(undefined, stateWith({})), false);
});

await test('only WARNING issues are listed in the body', () => {
  const html = exportGateHtml([
    geometryWarning(['m1']),
    { code: 'missing-source', severity: 'error', objectIds: ['m2'] },
  ], false);
  assert.equal((html.match(/<li>/g) ?? []).length, 1,
    'the error issue belongs to the blocked modal, not the gate');
});

console.log('\n' + out.join('\n'));
console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed ? 1 : 0);
