// Vite entrypoint. Builds the Babylon namespace expected by the migrated JS
// modules, then starts the app bootstrap.

import {
  AbstractMesh,
  Animation,
  ArcRotateCamera,
  AssetContainer,
  Axis,
  BaseTexture,
  Camera,
  Color3,
  Color4,
  CubeTexture,
  DirectionalLight,
  DynamicTexture,
  EasingFunction,
  Effect,
  Engine,
  GizmoManager,
  HemisphericLight,
  ImageProcessingConfiguration,
  Layer,
  Material,
  Matrix,
  Mesh,
  MeshBuilder,
  PBRMaterial,
  PBRMetallicRoughnessMaterial,
  PBRSpecularGlossinessMaterial,
  Plane,
  PointerEventTypes,
  PostProcess,
  QuadraticEase,
  Quaternion,
  Ray,
  RenderTargetTexture,
  Scene,
  SceneLoader,
  ShadowGenerator,
  SSAO2RenderingPipeline,
  StandardMaterial,
  Texture,
  Tools,
  TransformNode,
  Vector3,
  VertexBuffer,
  VertexData,
} from '@babylonjs/core';
import { GridMaterial, ShadowOnlyMaterial } from '@babylonjs/materials';
import { OBJExport, STLExport } from '@babylonjs/serializers';
import '@babylonjs/loaders';

declare global {
  interface Window {
    BABYLON?: Record<string, unknown>;
  }
}

window.BABYLON = {
  ...(window.BABYLON ?? {}),
  AbstractMesh,
  Animation,
  ArcRotateCamera,
  AssetContainer,
  Axis,
  BaseTexture,
  Camera,
  Color3,
  Color4,
  CubeTexture,
  DirectionalLight,
  DynamicTexture,
  EasingFunction,
  Effect,
  Engine,
  GizmoManager,
  GridMaterial,
  HemisphericLight,
  ImageProcessingConfiguration,
  Layer,
  Material,
  Matrix,
  Mesh,
  MeshBuilder,
  OBJExport,
  PBRMaterial,
  PBRMetallicRoughnessMaterial,
  PBRSpecularGlossinessMaterial,
  Plane,
  PointerEventTypes,
  PostProcess,
  QuadraticEase,
  Quaternion,
  Ray,
  RenderTargetTexture,
  Scene,
  SceneLoader,
  ShadowGenerator,
  ShadowOnlyMaterial,
  SSAO2RenderingPipeline,
  StandardMaterial,
  STLExport,
  Texture,
  Tools,
  TransformNode,
  Vector3,
  VertexBuffer,
  VertexData,
};

await import('./main');
